name: human-face-emotion-detection-and-recognition

services:
  human-face-emotion-detection-and-recognition:
    image: human-face-emotion-detection-and-recognition:latest
    build:
      context: .
    ports:
      - "8000:8000"
    restart: unless-stopped
    environment:
      OMP_NUM_THREADS: "1"
      OPENBLAS_NUM_THREADS: "1"
    deploy:
      resources:
        limits:
          memory: 1G
